export type CareerDemandTrend = "growing" | "stable" | "declining";
export type EducationCostBand = "low" | "medium" | "high";

export interface CareerTaxonomyEntry {
  key: string;
  name: string;
  family: string;
  interestTags: string[];
  subjectTags: string[];
  hobbyTags: string[];
  workStyle: {
    collaboration: number;
    structure: number;
    creativity: number;
    analysis: number;
    people: number;
    field: number;
    risk: number;
    pace: number;
  };
  preferredStudy: "theory" | "applied" | "balanced";
  educationCostBand: EducationCostBand;
  locationModes: Array<"home-city" | "anywhere-india" | "remote" | "global">;
  salaryBandEntry: string;
  salaryBandMid: string;
  salaryBandSenior: string;
  demandTrend: CareerDemandTrend;
  description: string;
  starterSkills: string[];
}

interface CareerFamily {
  family: string;
  titles: [string, string, string, string, string, string];
  interests: string[];
  subjects: string[];
  hobbies: string[];
  style: CareerTaxonomyEntry["workStyle"];
  study: CareerTaxonomyEntry["preferredStudy"];
  cost: EducationCostBand;
  locations: CareerTaxonomyEntry["locationModes"];
  salary: [string, string, string];
  demand: CareerDemandTrend;
  overview: string;
  skills: string[];
}

const allLocations: CareerTaxonomyEntry["locationModes"] = [
  "home-city",
  "anywhere-india",
  "remote",
  "global",
];

const careerFamilies: CareerFamily[] = [
  {
    family: "Software & Data",
    titles: ["Software Engineer", "Data Analyst", "Data Scientist", "Cybersecurity Analyst", "Cloud Engineer", "AI/ML Engineer"],
    interests: ["Technology", "Building things", "Solving puzzles"],
    subjects: ["Mathematics", "Computer Science", "Physics"],
    hobbies: ["Coding", "Gaming", "Building things"],
    style: { collaboration: 3, structure: 4, creativity: 4, analysis: 5, people: 2, field: 1, risk: 3, pace: 4 },
    study: "applied",
    cost: "medium",
    locations: allLocations,
    salary: ["₹5-10L", "₹12-25L", "₹28-60L+"],
    demand: "growing",
    overview: "builds and improves digital systems using computation, evidence, and iterative problem-solving",
    skills: ["Programming", "Data structures", "Systems thinking"],
  },
  {
    family: "Design & Experience",
    titles: ["Product Designer", "UI/UX Designer", "Graphic Designer", "Interaction Designer", "Service Designer", "Motion Designer"],
    interests: ["Design", "Art", "Technology"],
    subjects: ["Art", "Computer Science", "Psychology"],
    hobbies: ["Drawing", "Photography", "Making videos"],
    style: { collaboration: 4, structure: 3, creativity: 5, analysis: 3, people: 4, field: 2, risk: 3, pace: 4 },
    study: "applied",
    cost: "medium",
    locations: allLocations,
    salary: ["₹4-8L", "₹10-20L", "₹22-45L+"],
    demand: "growing",
    overview: "turns human needs into clear, useful, and engaging products, services, and visual systems",
    skills: ["Visual communication", "User research", "Prototyping"],
  },
  {
    family: "Business & Strategy",
    titles: ["Product Manager", "Business Analyst", "Management Consultant", "Operations Manager", "Strategy Analyst", "Entrepreneur"],
    interests: ["Business", "Leadership", "Technology"],
    subjects: ["Economics", "Business Studies", "Mathematics"],
    hobbies: ["Organising events", "Debating", "Building things"],
    style: { collaboration: 5, structure: 4, creativity: 4, analysis: 4, people: 5, field: 2, risk: 4, pace: 5 },
    study: "balanced",
    cost: "medium",
    locations: ["anywhere-india", "remote", "global"],
    salary: ["₹6-12L", "₹15-30L", "₹35-70L+"],
    demand: "growing",
    overview: "aligns people, evidence, and commercial goals to make organisations and products work better",
    skills: ["Communication", "Market analysis", "Prioritisation"],
  },
  {
    family: "Medicine & Allied Health",
    titles: ["Doctor", "Physiotherapist", "Clinical Psychologist", "Occupational Therapist", "Nutritionist", "Public Health Specialist"],
    interests: ["Healthcare", "Helping people", "Science"],
    subjects: ["Biology", "Chemistry", "Psychology"],
    hobbies: ["Volunteering", "Sports", "Reading"],
    style: { collaboration: 5, structure: 5, creativity: 2, analysis: 5, people: 5, field: 4, risk: 2, pace: 5 },
    study: "theory",
    cost: "high",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹4-10L", "₹10-25L", "₹25-60L+"],
    demand: "growing",
    overview: "uses scientific knowledge and human care to prevent, diagnose, or improve health outcomes",
    skills: ["Biology", "Clinical reasoning", "Empathy"],
  },
  {
    family: "Finance & Markets",
    titles: ["Chartered Accountant", "Investment Analyst", "Financial Planner", "Risk Analyst", "Equity Research Analyst", "FinTech Analyst"],
    interests: ["Finance", "Business", "Solving puzzles"],
    subjects: ["Accountancy", "Mathematics", "Economics"],
    hobbies: ["Investing", "Reading", "Solving puzzles"],
    style: { collaboration: 3, structure: 5, creativity: 2, analysis: 5, people: 3, field: 1, risk: 3, pace: 4 },
    study: "theory",
    cost: "medium",
    locations: ["anywhere-india", "remote", "global"],
    salary: ["₹5-10L", "₹12-28L", "₹30-75L+"],
    demand: "stable",
    overview: "uses financial evidence, controls, and market context to guide decisions and manage risk",
    skills: ["Financial modelling", "Accounting", "Attention to detail"],
  },
  {
    family: "Law, Policy & Governance",
    titles: ["Corporate Lawyer", "Litigation Lawyer", "Policy Analyst", "Legal Researcher", "Compliance Officer", "Civil Services Officer"],
    interests: ["Law", "Public service", "Debating"],
    subjects: ["Political Science", "History", "English"],
    hobbies: ["Debating", "Reading", "Volunteering"],
    style: { collaboration: 4, structure: 5, creativity: 3, analysis: 5, people: 4, field: 3, risk: 2, pace: 4 },
    study: "theory",
    cost: "medium",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹4-9L", "₹10-24L", "₹25-65L+"],
    demand: "stable",
    overview: "interprets rules, evidence, and public goals to protect rights and improve institutions",
    skills: ["Legal reasoning", "Research", "Persuasive writing"],
  },
  {
    family: "Education & Learning",
    titles: ["School Teacher", "Instructional Designer", "Education Technologist", "Academic Counselor", "Special Educator", "Curriculum Developer"],
    interests: ["Education", "Helping people", "Technology"],
    subjects: ["English", "Psychology", "Computer Science"],
    hobbies: ["Teaching", "Reading", "Volunteering"],
    style: { collaboration: 5, structure: 4, creativity: 4, analysis: 3, people: 5, field: 2, risk: 2, pace: 3 },
    study: "balanced",
    cost: "low",
    locations: allLocations,
    salary: ["₹3-7L", "₹7-15L", "₹16-32L+"],
    demand: "growing",
    overview: "designs and delivers learning experiences that help different kinds of learners progress",
    skills: ["Teaching", "Curriculum design", "Communication"],
  },
  {
    family: "Media & Communication",
    titles: ["Journalist", "Content Strategist", "Film Editor", "Digital Producer", "Public Relations Specialist", "Technical Writer"],
    interests: ["Media", "Writing", "Current affairs"],
    subjects: ["English", "Political Science", "Art"],
    hobbies: ["Writing", "Photography", "Making videos"],
    style: { collaboration: 4, structure: 3, creativity: 5, analysis: 3, people: 4, field: 3, risk: 4, pace: 5 },
    study: "applied",
    cost: "medium",
    locations: allLocations,
    salary: ["₹3-7L", "₹8-18L", "₹20-45L+"],
    demand: "stable",
    overview: "researches, shapes, and distributes stories and information for specific audiences",
    skills: ["Writing", "Storytelling", "Audience research"],
  },
  {
    family: "Core Engineering",
    titles: ["Mechanical Engineer", "Electrical Engineer", "Civil Engineer", "Chemical Engineer", "Electronics Engineer", "Industrial Engineer"],
    interests: ["Engineering", "Building things", "Science"],
    subjects: ["Physics", "Mathematics", "Chemistry"],
    hobbies: ["Building things", "Robotics", "Repairing things"],
    style: { collaboration: 4, structure: 5, creativity: 3, analysis: 5, people: 2, field: 4, risk: 2, pace: 3 },
    study: "applied",
    cost: "medium",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹4-8L", "₹9-20L", "₹22-45L+"],
    demand: "stable",
    overview: "applies mathematics and physical science to design dependable real-world systems and infrastructure",
    skills: ["Engineering fundamentals", "CAD", "Problem solving"],
  },
  {
    family: "Architecture & Built Environment",
    titles: ["Architect", "Urban Planner", "Interior Designer", "Landscape Architect", "Sustainability Consultant", "Construction Manager"],
    interests: ["Design", "Cities", "Building things"],
    subjects: ["Mathematics", "Art", "Geography"],
    hobbies: ["Drawing", "Photography", "Building things"],
    style: { collaboration: 4, structure: 4, creativity: 5, analysis: 4, people: 3, field: 4, risk: 2, pace: 4 },
    study: "applied",
    cost: "high",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹4-8L", "₹9-20L", "₹22-45L+"],
    demand: "stable",
    overview: "combines spatial design, technical constraints, and community needs to shape the built environment",
    skills: ["Spatial thinking", "Design software", "Technical drawing"],
  },
  {
    family: "Life Sciences & Biotech",
    titles: ["Biotechnologist", "Microbiologist", "Genetic Counselor", "Biomedical Researcher", "Food Scientist", "Clinical Research Associate"],
    interests: ["Science", "Healthcare", "Research"],
    subjects: ["Biology", "Chemistry", "Mathematics"],
    hobbies: ["Experiments", "Reading", "Gardening"],
    style: { collaboration: 3, structure: 5, creativity: 3, analysis: 5, people: 2, field: 2, risk: 2, pace: 3 },
    study: "theory",
    cost: "medium",
    locations: ["anywhere-india", "global"],
    salary: ["₹4-8L", "₹9-19L", "₹20-42L+"],
    demand: "growing",
    overview: "investigates living systems and translates biological evidence into health, food, and industrial solutions",
    skills: ["Laboratory methods", "Scientific writing", "Statistics"],
  },
  {
    family: "Environment & Sustainability",
    titles: ["Environmental Scientist", "Climate Analyst", "Renewable Energy Specialist", "Conservation Biologist", "ESG Analyst", "Waste Management Specialist"],
    interests: ["Environment", "Science", "Public service"],
    subjects: ["Geography", "Biology", "Chemistry"],
    hobbies: ["Gardening", "Trekking", "Volunteering"],
    style: { collaboration: 4, structure: 4, creativity: 3, analysis: 4, people: 3, field: 5, risk: 2, pace: 3 },
    study: "balanced",
    cost: "medium",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹4-8L", "₹9-18L", "₹20-40L+"],
    demand: "growing",
    overview: "uses science, policy, and systems thinking to reduce environmental harm and improve resilience",
    skills: ["Environmental science", "Data analysis", "Field research"],
  },
  {
    family: "Public Service & Development",
    titles: ["Development Sector Consultant", "Social Researcher", "Program Manager", "Urban Governance Specialist", "International Relations Analyst", "Disaster Management Officer"],
    interests: ["Public service", "Helping people", "Current affairs"],
    subjects: ["Political Science", "Economics", "Geography"],
    hobbies: ["Volunteering", "Debating", "Reading"],
    style: { collaboration: 5, structure: 4, creativity: 3, analysis: 4, people: 5, field: 4, risk: 3, pace: 4 },
    study: "balanced",
    cost: "low",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹4-8L", "₹9-18L", "₹20-40L+"],
    demand: "stable",
    overview: "coordinates evidence, communities, and institutions to improve public outcomes at scale",
    skills: ["Program management", "Policy analysis", "Stakeholder communication"],
  },
  {
    family: "Hospitality & Tourism",
    titles: ["Hotel Manager", "Travel Experience Designer", "Chef", "Event Manager", "Tourism Marketing Specialist", "Guest Relations Manager"],
    interests: ["Travel", "Food", "Helping people"],
    subjects: ["Business Studies", "English", "Geography"],
    hobbies: ["Cooking", "Travelling", "Organising events"],
    style: { collaboration: 5, structure: 4, creativity: 4, analysis: 2, people: 5, field: 4, risk: 3, pace: 5 },
    study: "applied",
    cost: "medium",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹3-7L", "₹8-17L", "₹18-38L+"],
    demand: "stable",
    overview: "creates and operates service experiences where detail, teamwork, and guest trust matter",
    skills: ["Service operations", "Communication", "Hospitality management"],
  },
  {
    family: "Skilled Technology Trades",
    titles: ["Mechatronics Technician", "Electric Vehicle Technician", "Drone Technician", "Industrial Automation Technician", "Solar Installation Specialist", "CNC Programmer"],
    interests: ["Technology", "Engineering", "Building things"],
    subjects: ["Physics", "Mathematics", "Computer Science"],
    hobbies: ["Repairing things", "Robotics", "Building things"],
    style: { collaboration: 3, structure: 5, creativity: 3, analysis: 4, people: 2, field: 5, risk: 2, pace: 4 },
    study: "applied",
    cost: "low",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹3-6L", "₹7-14L", "₹15-28L+"],
    demand: "growing",
    overview: "installs, operates, and troubleshoots advanced physical technology through hands-on technical expertise",
    skills: ["Technical diagnostics", "Safety", "Equipment operation"],
  },
  {
    family: "Sports & Wellness",
    titles: ["Sports Scientist", "Strength and Conditioning Coach", "Sports Physiotherapist", "Performance Analyst", "Fitness Entrepreneur", "Sports Psychologist"],
    interests: ["Sports", "Healthcare", "Helping people"],
    subjects: ["Biology", "Physical Education", "Psychology"],
    hobbies: ["Sports", "Fitness", "Coaching"],
    style: { collaboration: 5, structure: 4, creativity: 3, analysis: 3, people: 5, field: 5, risk: 3, pace: 5 },
    study: "applied",
    cost: "medium",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹3-7L", "₹8-18L", "₹20-45L+"],
    demand: "growing",
    overview: "combines performance science, coaching, and behavior change to help people move and compete better",
    skills: ["Exercise science", "Coaching", "Performance measurement"],
  },
  {
    family: "Creative Arts",
    titles: ["Illustrator", "Animator", "Photographer", "Music Producer", "Writer", "Art Director"],
    interests: ["Art", "Music", "Writing"],
    subjects: ["Art", "English", "Music"],
    hobbies: ["Drawing", "Photography", "Making music"],
    style: { collaboration: 3, structure: 2, creativity: 5, analysis: 2, people: 3, field: 2, risk: 5, pace: 3 },
    study: "applied",
    cost: "low",
    locations: allLocations,
    salary: ["₹3-7L", "₹8-18L", "₹20-50L+"],
    demand: "stable",
    overview: "creates original visual, written, or audio work that communicates ideas and builds cultural value",
    skills: ["Creative craft", "Portfolio building", "Storytelling"],
  },
  {
    family: "Psychology & Social Impact",
    titles: ["Counseling Psychologist", "Behavioral Researcher", "Social Worker", "Organizational Psychologist", "Child Development Specialist", "Community Program Designer"],
    interests: ["Psychology", "Helping people", "Research"],
    subjects: ["Psychology", "Biology", "Sociology"],
    hobbies: ["Volunteering", "Reading", "Teaching"],
    style: { collaboration: 5, structure: 4, creativity: 3, analysis: 4, people: 5, field: 3, risk: 2, pace: 3 },
    study: "theory",
    cost: "medium",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹3-7L", "₹8-17L", "₹18-38L+"],
    demand: "growing",
    overview: "uses behavioral evidence and empathetic practice to improve individual and community wellbeing",
    skills: ["Active listening", "Research methods", "Ethics"],
  },
  {
    family: "Agriculture & Food Systems",
    titles: ["Agricultural Scientist", "Agribusiness Manager", "Precision Agriculture Specialist", "Food Supply Chain Analyst", "Horticulturist", "Rural Development Officer"],
    interests: ["Agriculture", "Environment", "Business"],
    subjects: ["Biology", "Geography", "Economics"],
    hobbies: ["Gardening", "Trekking", "Building things"],
    style: { collaboration: 4, structure: 4, creativity: 3, analysis: 4, people: 4, field: 5, risk: 3, pace: 3 },
    study: "applied",
    cost: "low",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹3-7L", "₹8-16L", "₹18-35L+"],
    demand: "growing",
    overview: "improves how food and agricultural products are grown, financed, processed, and distributed",
    skills: ["Crop science", "Data collection", "Supply chain basics"],
  },
  {
    family: "Aviation & Maritime",
    titles: ["Commercial Pilot", "Aircraft Maintenance Engineer", "Aerospace Operations Analyst", "Merchant Navy Officer", "Marine Engineer", "Airport Operations Manager"],
    interests: ["Travel", "Engineering", "Technology"],
    subjects: ["Physics", "Mathematics", "Geography"],
    hobbies: ["Travelling", "Model building", "Sports"],
    style: { collaboration: 5, structure: 5, creativity: 2, analysis: 5, people: 3, field: 5, risk: 2, pace: 5 },
    study: "applied",
    cost: "high",
    locations: ["anywhere-india", "global"],
    salary: ["₹5-12L", "₹14-32L", "₹35-80L+"],
    demand: "stable",
    overview: "operates and maintains safety-critical transport systems across air, sea, and complex terminals",
    skills: ["Safety procedures", "Technical systems", "Situational awareness"],
  },
  {
    family: "Defence & Security",
    titles: ["Armed Forces Officer", "Defence Technology Analyst", "Intelligence Analyst", "Forensic Scientist", "Emergency Response Planner", "Security Risk Consultant"],
    interests: ["Public service", "Technology", "Fitness"],
    subjects: ["Political Science", "Physics", "Mathematics"],
    hobbies: ["Sports", "Current affairs", "Trekking"],
    style: { collaboration: 5, structure: 5, creativity: 2, analysis: 4, people: 4, field: 5, risk: 2, pace: 5 },
    study: "balanced",
    cost: "low",
    locations: ["anywhere-india", "global"],
    salary: ["₹5-10L", "₹11-24L", "₹25-48L+"],
    demand: "stable",
    overview: "protects people and institutions through disciplined operations, evidence, and preparedness",
    skills: ["Leadership", "Risk assessment", "Physical readiness"],
  },
  {
    family: "Research & Academia",
    titles: ["University Researcher", "Economist", "Mathematician", "Experimental Physicist", "Research Methodologist", "Science Communicator"],
    interests: ["Research", "Science", "Solving puzzles"],
    subjects: ["Mathematics", "Physics", "Economics"],
    hobbies: ["Reading", "Experiments", "Writing"],
    style: { collaboration: 3, structure: 4, creativity: 4, analysis: 5, people: 2, field: 2, risk: 3, pace: 2 },
    study: "theory",
    cost: "medium",
    locations: ["anywhere-india", "remote", "global"],
    salary: ["₹4-8L", "₹9-20L", "₹22-48L+"],
    demand: "stable",
    overview: "creates and tests new knowledge through rigorous questions, methods, evidence, and communication",
    skills: ["Research design", "Statistics", "Academic writing"],
  },
  {
    family: "Marketing & Growth",
    titles: ["Digital Marketer", "Brand Strategist", "Growth Analyst", "Consumer Insights Researcher", "Sales Engineer", "Community Manager"],
    interests: ["Business", "Media", "Psychology"],
    subjects: ["Business Studies", "Psychology", "English"],
    hobbies: ["Making videos", "Organising events", "Writing"],
    style: { collaboration: 5, structure: 3, creativity: 5, analysis: 3, people: 5, field: 2, risk: 4, pace: 5 },
    study: "applied",
    cost: "low",
    locations: allLocations,
    salary: ["₹4-8L", "₹9-20L", "₹22-50L+"],
    demand: "growing",
    overview: "combines audience insight, experimentation, and storytelling to grow demand and trusted communities",
    skills: ["Market research", "Copywriting", "Analytics"],
  },
  {
    family: "People & Organisations",
    titles: ["Human Resources Partner", "Talent Acquisition Specialist", "Learning and Development Manager", "People Analyst", "Organizational Development Consultant", "Employee Experience Designer"],
    interests: ["Helping people", "Business", "Psychology"],
    subjects: ["Psychology", "Business Studies", "Sociology"],
    hobbies: ["Organising events", "Volunteering", "Teaching"],
    style: { collaboration: 5, structure: 4, creativity: 3, analysis: 3, people: 5, field: 2, risk: 2, pace: 4 },
    study: "balanced",
    cost: "low",
    locations: allLocations,
    salary: ["₹4-8L", "₹9-20L", "₹22-45L+"],
    demand: "stable",
    overview: "builds fair, effective systems that help people join, learn, contribute, and thrive at work",
    skills: ["People operations", "Communication", "Workplace analytics"],
  },
  {
    family: "Games & Immersive Media",
    titles: ["Game Designer", "Game Developer", "3D Artist", "Technical Artist", "Level Designer", "XR Developer"],
    interests: ["Gaming", "Technology", "Art"],
    subjects: ["Computer Science", "Art", "Mathematics"],
    hobbies: ["Gaming", "Coding", "Drawing"],
    style: { collaboration: 4, structure: 3, creativity: 5, analysis: 4, people: 2, field: 1, risk: 4, pace: 5 },
    study: "applied",
    cost: "medium",
    locations: ["anywhere-india", "remote", "global"],
    salary: ["₹4-9L", "₹10-22L", "₹24-50L+"],
    demand: "growing",
    overview: "combines code, visual craft, systems, and storytelling to create interactive experiences",
    skills: ["Game engines", "Interaction design", "3D fundamentals"],
  },
  {
    family: "Language & Global Communication",
    titles: ["Translator", "Interpreter", "Localization Specialist", "Linguist", "Foreign Language Trainer", "Diplomatic Communications Specialist"],
    interests: ["Languages", "Travel", "Writing"],
    subjects: ["English", "Foreign Languages", "History"],
    hobbies: ["Reading", "Travelling", "Writing"],
    style: { collaboration: 4, structure: 4, creativity: 4, analysis: 4, people: 4, field: 2, risk: 2, pace: 3 },
    study: "theory",
    cost: "low",
    locations: allLocations,
    salary: ["₹3-7L", "₹8-17L", "₹18-38L+"],
    demand: "stable",
    overview: "bridges cultures and systems through precise language, context, and audience-aware communication",
    skills: ["Language fluency", "Cultural context", "Editing"],
  },
  {
    family: "Quantitative Risk & Insurance",
    titles: ["Actuary", "Quantitative Analyst", "Insurance Product Analyst", "Credit Risk Modeler", "Fraud Analyst", "Operations Research Analyst"],
    interests: ["Finance", "Solving puzzles", "Research"],
    subjects: ["Mathematics", "Statistics", "Economics"],
    hobbies: ["Solving puzzles", "Investing", "Coding"],
    style: { collaboration: 2, structure: 5, creativity: 3, analysis: 5, people: 2, field: 1, risk: 2, pace: 3 },
    study: "theory",
    cost: "medium",
    locations: ["anywhere-india", "remote", "global"],
    salary: ["₹6-12L", "₹15-32L", "₹35-75L+"],
    demand: "growing",
    overview: "turns uncertainty into measurable models that guide financial and operational decisions",
    skills: ["Probability", "Statistics", "Financial mathematics"],
  },
  {
    family: "Supply Chain & Logistics",
    titles: ["Supply Chain Analyst", "Logistics Manager", "Procurement Specialist", "Warehouse Automation Planner", "Trade Compliance Analyst", "Demand Planner"],
    interests: ["Business", "Technology", "Solving puzzles"],
    subjects: ["Business Studies", "Mathematics", "Geography"],
    hobbies: ["Organising events", "Building things", "Travelling"],
    style: { collaboration: 4, structure: 5, creativity: 2, analysis: 5, people: 3, field: 4, risk: 2, pace: 5 },
    study: "applied",
    cost: "low",
    locations: ["home-city", "anywhere-india", "global"],
    salary: ["₹4-8L", "₹9-20L", "₹22-45L+"],
    demand: "growing",
    overview: "coordinates the movement of materials, information, and money across complex networks",
    skills: ["Operations planning", "Excel and analytics", "Vendor management"],
  },
  {
    family: "Fashion & Lifestyle",
    titles: ["Fashion Designer", "Textile Designer", "Fashion Merchandiser", "Costume Designer", "Sustainable Fashion Specialist", "Luxury Brand Manager"],
    interests: ["Fashion", "Design", "Business"],
    subjects: ["Art", "Business Studies", "English"],
    hobbies: ["Drawing", "Photography", "Crafts"],
    style: { collaboration: 4, structure: 3, creativity: 5, analysis: 2, people: 4, field: 3, risk: 4, pace: 5 },
    study: "applied",
    cost: "high",
    locations: ["anywhere-india", "remote", "global"],
    salary: ["₹3-7L", "₹8-18L", "₹20-48L+"],
    demand: "stable",
    overview: "combines aesthetic judgment, materials, culture, and commercial insight to create lifestyle products",
    skills: ["Design development", "Materials", "Trend research"],
  },
  {
    family: "Earth, Space & Geoscience",
    titles: ["Geologist", "GIS Analyst", "Meteorologist", "Space Systems Analyst", "Remote Sensing Specialist", "Geophysicist"],
    interests: ["Science", "Space", "Environment"],
    subjects: ["Geography", "Physics", "Mathematics"],
    hobbies: ["Trekking", "Astronomy", "Experiments"],
    style: { collaboration: 3, structure: 4, creativity: 3, analysis: 5, people: 2, field: 5, risk: 3, pace: 3 },
    study: "theory",
    cost: "medium",
    locations: ["anywhere-india", "global"],
    salary: ["₹4-9L", "₹10-22L", "₹24-50L+"],
    demand: "growing",
    overview: "uses physical science and spatial data to understand Earth, weather, resources, and space systems",
    skills: ["Geospatial analysis", "Physics", "Field methods"],
  },
  {
    family: "Robotics & Emerging Hardware",
    titles: ["Robotics Engineer", "Embedded Systems Engineer", "IoT Engineer", "Semiconductor Design Engineer", "Automation Engineer", "Human-Robot Interaction Researcher"],
    interests: ["Technology", "Engineering", "Robotics"],
    subjects: ["Physics", "Mathematics", "Computer Science"],
    hobbies: ["Robotics", "Coding", "Building things"],
    style: { collaboration: 4, structure: 4, creativity: 5, analysis: 5, people: 2, field: 3, risk: 3, pace: 4 },
    study: "applied",
    cost: "high",
    locations: ["anywhere-india", "global"],
    salary: ["₹5-10L", "₹12-26L", "₹28-60L+"],
    demand: "growing",
    overview: "integrates software, electronics, and mechanics to make intelligent physical systems dependable",
    skills: ["Electronics", "Programming", "Control systems"],
  },
  {
    family: "Commerce & Entrepreneurship",
    titles: ["E-commerce Manager", "Small Business Founder", "Retail Operations Manager", "Export Business Specialist", "Franchise Consultant", "Social Enterprise Founder"],
    interests: ["Business", "Leadership", "Finance"],
    subjects: ["Business Studies", "Accountancy", "Economics"],
    hobbies: ["Organising events", "Investing", "Making videos"],
    style: { collaboration: 5, structure: 3, creativity: 4, analysis: 3, people: 5, field: 3, risk: 5, pace: 5 },
    study: "applied",
    cost: "low",
    locations: allLocations,
    salary: ["₹3-8L", "₹9-22L", "₹25-70L+"],
    demand: "growing",
    overview: "identifies customer needs and builds practical commercial systems to serve them sustainably",
    skills: ["Sales", "Cash-flow basics", "Customer discovery"],
  },
];

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const careerTaxonomy: CareerTaxonomyEntry[] = careerFamilies.flatMap(
  (family) =>
    family.titles.map((name) => ({
      key: slugify(name),
      name,
      family: family.family,
      interestTags: family.interests,
      subjectTags: family.subjects,
      hobbyTags: family.hobbies,
      workStyle: family.style,
      preferredStudy: family.study,
      educationCostBand: family.cost,
      locationModes: family.locations,
      salaryBandEntry: family.salary[0],
      salaryBandMid: family.salary[1],
      salaryBandSenior: family.salary[2],
      demandTrend: family.demand,
      description: `${name} ${family.overview}.`,
      starterSkills: family.skills,
    })),
);
