export interface ExamCatalogEntry {
  id: string;
  name: string;
  shortName: string;
  category: string;
  careerTerms: string[];
  locations: string[];
  collegeOwnership: Array<"government" | "private">;
  difficulty: number;
  eligibilitySummary: string;
  acceptedCollegesCountDemo: number;
  advantages: string[];
  tips: [string, string, string];
  mockDates: { application: string; exam: string; result: string };
  officialUrl: string;
}

const dates = (application: string, exam: string, result: string) => ({ application, exam, result });

export const examCatalog: ExamCatalogEntry[] = [
  { id: "jee-main", name: "Joint Entrance Examination Main", shortName: "JEE Main", category: "Engineering", careerTerms: ["engineering", "software", "data", "technology", "architecture"], locations: ["All India"], collegeOwnership: ["government", "private"], difficulty: 4, eligibilitySummary: "Class 12 with Physics and Mathematics; subject rules vary by program.", acceptedCollegesCountDemo: 1200, advantages: ["Gateway to NITs, IIITs, and many state/private institutions", "Also qualifies eligible students for JEE Advanced"], tips: ["Build a weekly Physics-Chemistry-Mathematics error log.", "Mix timed chapter tests with full-length mocks.", "Verify current eligibility rules before applying."], mockDates: dates("Demo: Nov-Jan", "Demo: Jan and Apr", "Demo: Feb and May"), officialUrl: "https://jeemain.nta.nic.in/" },
  { id: "jee-advanced", name: "Joint Entrance Examination Advanced", shortName: "JEE Advanced", category: "Engineering", careerTerms: ["engineering", "software", "data", "technology", "science"], locations: ["All India"], collegeOwnership: ["government"], difficulty: 5, eligibilitySummary: "Requires qualifying JEE Main and meeting the current official eligibility rules.", acceptedCollegesCountDemo: 23, advantages: ["Primary undergraduate route to the IITs", "Strong research and interdisciplinary pathways"], tips: ["Prioritize multi-concept problems over formula repetition.", "Review solutions for method quality, not only correctness.", "Use official past papers under timed conditions."], mockDates: dates("Demo: Apr-May", "Demo: May-Jun", "Demo: Jun"), officialUrl: "https://jeeadv.ac.in/" },
  { id: "bitsat", name: "BITS Admission Test", shortName: "BITSAT", category: "Engineering", careerTerms: ["engineering", "software", "data", "technology", "science"], locations: ["Rajasthan", "Goa", "Telangana", "All India"], collegeOwnership: ["private"], difficulty: 4, eligibilitySummary: "Class 12 subject and minimum-mark requirements depend on the selected program.", acceptedCollegesCountDemo: 3, advantages: ["Flexible first-degree and dual-degree options", "Multiple test-session structure in a typical cycle"], tips: ["Train speed across the complete syllabus.", "Do not neglect English proficiency and logical reasoning.", "Use the official syllabus as the final scope."], mockDates: dates("Demo: Jan-Apr", "Demo: May-Jun", "Demo: Jun-Jul"), officialUrl: "https://www.bitsadmission.com/" },
  { id: "cuet-ug", name: "Common University Entrance Test Undergraduate", shortName: "CUET UG", category: "Multi-disciplinary", careerTerms: ["business", "economics", "science", "arts", "design", "software", "data", "law", "psychology"], locations: ["All India"], collegeOwnership: ["government", "private"], difficulty: 3, eligibilitySummary: "Class 12; required domain subjects depend on each university and program.", acceptedCollegesCountDemo: 250, advantages: ["One route to many central and participating universities", "Covers a wide range of degree families"], tips: ["Map every target program to its required CUET subjects.", "Practice language and domain sections separately.", "Recheck each university's combination rules."], mockDates: dates("Demo: Feb-Mar", "Demo: May-Jun", "Demo: Jul"), officialUrl: "https://cuet.nta.nic.in/" },
  { id: "comedk", name: "COMEDK Undergraduate Entrance Test", shortName: "COMEDK UGET", category: "Engineering", careerTerms: ["engineering", "software", "data", "technology"], locations: ["Karnataka", "All India"], collegeOwnership: ["private"], difficulty: 3, eligibilitySummary: "Class 12 with Physics, Mathematics, and the officially specified optional subject.", acceptedCollegesCountDemo: 150, advantages: ["Single test for participating Karnataka private colleges", "Useful alternative to state-domicile routes"], tips: ["Practice fast, accurate PCM question selection.", "Track negative patterns after every mock.", "Compare counselling fees before choice filling."], mockDates: dates("Demo: Feb-Apr", "Demo: May", "Demo: Jun"), officialUrl: "https://www.comedk.org/" },
  { id: "mht-cet", name: "Maharashtra Common Entrance Test", shortName: "MHT CET", category: "Engineering and Pharmacy", careerTerms: ["engineering", "software", "data", "technology", "pharmacy"], locations: ["Maharashtra", "All India"], collegeOwnership: ["government", "private"], difficulty: 3, eligibilitySummary: "Class 12 subject eligibility and candidature type follow Maharashtra CET Cell rules.", acceptedCollegesCountDemo: 500, advantages: ["Major route to Maharashtra engineering and pharmacy seats", "Wide mix of government and private choices"], tips: ["Align revision to the official state-board-weighted syllabus.", "Practice speed because question volume is high.", "Understand domicile and candidature documents early."], mockDates: dates("Demo: Dec-Feb", "Demo: Apr-May", "Demo: Jun"), officialUrl: "https://cetcell.mahacet.org/" },
  { id: "viteee", name: "VIT Engineering Entrance Examination", shortName: "VITEEE", category: "Engineering", careerTerms: ["engineering", "software", "data", "technology"], locations: ["Tamil Nadu", "Andhra Pradesh", "Madhya Pradesh", "All India"], collegeOwnership: ["private"], difficulty: 3, eligibilitySummary: "Class 12 PCM/PCB combination depends on the engineering program selected.", acceptedCollegesCountDemo: 4, advantages: ["Direct route to VIT campuses", "Broad engineering branch selection"], tips: ["Revise full PCM breadth instead of over-specializing.", "Take computer-based mocks regularly.", "Review fee categories before counselling."], mockDates: dates("Demo: Nov-Mar", "Demo: Apr", "Demo: May"), officialUrl: "https://viteee.vit.ac.in/" },
  { id: "kcet", name: "Karnataka Common Entrance Test", shortName: "KCET", category: "Engineering and Professional", careerTerms: ["engineering", "software", "agriculture", "pharmacy"], locations: ["Karnataka"], collegeOwnership: ["government", "private"], difficulty: 3, eligibilitySummary: "Eligibility and reservation benefits depend on Karnataka rules and qualifying subjects.", acceptedCollegesCountDemo: 220, advantages: ["Cost-effective route for eligible Karnataka candidates", "Covers several professional programs"], tips: ["Study the official Karnataka syllabus mapping.", "Prepare required study and domicile documents.", "Practice subject-wise timed sets."], mockDates: dates("Demo: Jan-Feb", "Demo: Apr", "Demo: May-Jun"), officialUrl: "https://cetonline.karnataka.gov.in/kea/" },
  { id: "wbjee", name: "West Bengal Joint Entrance Examination", shortName: "WBJEE", category: "Engineering", careerTerms: ["engineering", "software", "data", "technology", "pharmacy"], locations: ["West Bengal", "All India"], collegeOwnership: ["government", "private"], difficulty: 4, eligibilitySummary: "Class 12 PCM and domicile rules vary by institution and seat category.", acceptedCollegesCountDemo: 110, advantages: ["Route to prominent West Bengal institutions", "Government and private options through one counselling process"], tips: ["Learn the category-wise marking scheme.", "Prioritize Mathematics accuracy and pace.", "Check domicile-dependent seat rules."], mockDates: dates("Demo: Dec-Jan", "Demo: Apr", "Demo: May-Jun"), officialUrl: "https://wbjeeb.nic.in/" },
  { id: "neet-ug", name: "National Eligibility cum Entrance Test Undergraduate", shortName: "NEET UG", category: "Medicine", careerTerms: ["medicine", "doctor", "health", "dentistry", "veterinary", "biology"], locations: ["All India"], collegeOwnership: ["government", "private"], difficulty: 5, eligibilitySummary: "Class 12 Physics, Chemistry, Biology/Biotechnology and official age/mark rules apply.", acceptedCollegesCountDemo: 700, advantages: ["National route for undergraduate medical admissions", "Single core exam across participating medical pathways"], tips: ["Use NCERT as the anchor for Biology and Chemistry.", "Schedule full-length papers at the official duration.", "Verify counselling and category rules separately."], mockDates: dates("Demo: Feb-Mar", "Demo: May", "Demo: Jun"), officialUrl: "https://neet.nta.nic.in/" },
  { id: "clat", name: "Common Law Admission Test", shortName: "CLAT", category: "Law", careerTerms: ["law", "legal", "policy", "advocate", "corporate law"], locations: ["All India"], collegeOwnership: ["government"], difficulty: 4, eligibilitySummary: "Class 12 and the current consortium minimum-mark rules apply for undergraduate admission.", acceptedCollegesCountDemo: 24, advantages: ["Primary route to participating National Law Universities", "Tests reading-intensive skills useful in law school"], tips: ["Build daily reading speed across news and long-form analysis.", "Practice passage-first legal reasoning without prior-law assumptions.", "Review mock errors by question type."], mockDates: dates("Demo: Jul-Oct", "Demo: Dec", "Demo: Dec-Jan"), officialUrl: "https://consortiumofnlus.ac.in/" },
  { id: "ca-foundation", name: "Chartered Accountancy Foundation", shortName: "CA Foundation", category: "Commerce", careerTerms: ["accounting", "finance", "audit", "tax", "commerce", "chartered accountant"], locations: ["All India"], collegeOwnership: ["government", "private"], difficulty: 4, eligibilitySummary: "Registration and Class 12 examination requirements follow ICAI rules.", acceptedCollegesCountDemo: 0, advantages: ["Direct first stage of the Chartered Accountancy pathway", "Can be prepared alongside a commerce degree"], tips: ["Balance objective and descriptive paper practice.", "Build accounting fundamentals before mock volume.", "Use only the current ICAI syllabus and notices."], mockDates: dates("Demo: cycle-dependent", "Demo: Jan/May/Sep", "Demo: cycle-dependent"), officialUrl: "https://www.icai.org/" },
  { id: "nid-dat", name: "National Institute of Design - Design Aptitude Test", shortName: "NID DAT", category: "Design", careerTerms: ["design", "product design", "ux", "visual", "animation"], locations: ["All India"], collegeOwnership: ["government"], difficulty: 4, eligibilitySummary: "Class 12 eligibility applies across streams; official age and attempt rules vary by cycle.", acceptedCollegesCountDemo: 7, advantages: ["Portfolio-oriented route to NID undergraduate programs", "Tests observation, ideation, and visual communication"], tips: ["Keep a daily observation and sketch journal.", "Explain design choices, not only final drawings.", "Practice timed creative problem framing."], mockDates: dates("Demo: Sep-Dec", "Demo: Dec-Jan", "Demo: Mar-May"), officialUrl: "https://admissions.nid.edu/" },
  { id: "nift", name: "National Institute of Fashion Technology Entrance Examination", shortName: "NIFT", category: "Design", careerTerms: ["fashion", "design", "textile", "visual", "management"], locations: ["All India"], collegeOwnership: ["government"], difficulty: 3, eligibilitySummary: "Program-specific Class 12 and age criteria follow the official admissions notice.", acceptedCollegesCountDemo: 18, advantages: ["National route to NIFT design and technology programs", "Combines creativity, aptitude, and program-specific evaluation"], tips: ["Practice visual storytelling under time pressure.", "Follow design, culture, and sustainability news.", "Map preparation to the exact program test pattern."], mockDates: dates("Demo: Nov-Jan", "Demo: Feb", "Demo: Mar-Apr"), officialUrl: "https://www.nift.ac.in/admission" },
  { id: "nchm-jee", name: "National Council for Hotel Management Joint Entrance Examination", shortName: "NCHM JEE", category: "Hospitality", careerTerms: ["hospitality", "hotel", "tourism", "management", "chef"], locations: ["All India"], collegeOwnership: ["government", "private"], difficulty: 2, eligibilitySummary: "Class 12 with English and the current NTA/NCHM eligibility requirements.", acceptedCollegesCountDemo: 75, advantages: ["Focused route to hospitality-management institutes", "National counselling across participating institutions"], tips: ["Practice numerical ability and reasoning for speed.", "Build service-sector general awareness.", "Keep English comprehension in the weekly plan."], mockDates: dates("Demo: Feb-Mar", "Demo: Apr-May", "Demo: Jun"), officialUrl: "https://exams.nta.ac.in/NCHM/" },
];
