import type { OpportunityCategory } from "@/features/pathpilot/schemas";

export interface RadarOpportunityFixture {
  id: string;
  title: string;
  category: OpportunityCategory;
  organizerLabel: string;
  format: "online" | "in-person" | "hybrid";
  location: string;
  skillLevel: "beginner" | "intermediate" | "advanced" | "all-levels";
  typicalTiming: string;
  description: string;
  tags: string[];
}

// These are intentionally program patterns, not claims about currently open programs.
// The UI enforces the demo label and never presents a fabricated deadline.
export const radarOpportunityFixtures: RadarOpportunityFixture[] = [
  {
    id: "radar-student-build-sprint",
    title: "Student product build sprint",
    category: "hackathon",
    organizerLabel: "University innovation cell pattern",
    format: "hybrid",
    location: "India-wide",
    skillLevel: "beginner",
    typicalTiming: "Often announced around semester breaks",
    description: "A short team sprint to research a student problem, prototype a solution, and present a working demo.",
    tags: ["prototyping", "teamwork", "product", "design", "programming"],
  },
  {
    id: "radar-civic-tech-challenge",
    title: "Civic technology challenge",
    category: "hackathon",
    organizerLabel: "Public-interest innovation program pattern",
    format: "online",
    location: "Remote",
    skillLevel: "intermediate",
    typicalTiming: "Common around themed innovation weeks",
    description: "Build a data or software prototype that improves access to a public service or local information.",
    tags: ["data analysis", "programming", "public policy", "social impact"],
  },
  {
    id: "radar-ai-responsibility-sprint",
    title: "Responsible AI prototype sprint",
    category: "hackathon",
    organizerLabel: "Technology community program pattern",
    format: "online",
    location: "Remote",
    skillLevel: "intermediate",
    typicalTiming: "Typically run as a weekend cohort",
    description: "Design and test a small AI-assisted workflow with an emphasis on evaluation, transparency, and safe use.",
    tags: ["machine learning", "ai fundamentals", "research", "programming"],
  },
  {
    id: "radar-merit-means-support",
    title: "Merit-cum-means education support",
    category: "scholarship",
    organizerLabel: "Education foundation program pattern",
    format: "online",
    location: "India-wide",
    skillLevel: "all-levels",
    typicalTiming: "Application windows commonly follow admission cycles",
    description: "Needs-based support patterns that usually combine academic evidence, family-income documentation, and a short statement of purpose.",
    tags: ["education", "financial support", "college", "academic achievement"],
  },
  {
    id: "radar-women-stem-support",
    title: "Women in STEM study grant",
    category: "scholarship",
    organizerLabel: "Industry foundation program pattern",
    format: "online",
    location: "India-wide",
    skillLevel: "all-levels",
    typicalTiming: "Often opens near the start of an academic year",
    description: "A representative grant pattern supporting eligible students entering or continuing science and technology programs.",
    tags: ["stem", "engineering", "science", "financial support"],
  },
  {
    id: "radar-portfolio-microgrant",
    title: "Student portfolio micro-grant",
    category: "scholarship",
    organizerLabel: "Creative learning fund pattern",
    format: "online",
    location: "Remote",
    skillLevel: "beginner",
    typicalTiming: "Usually offered in small rolling cohorts",
    description: "Small material or software support for a clearly scoped student project with a public learning log.",
    tags: ["portfolio building", "design", "research", "project management"],
  },
  {
    id: "radar-data-storytelling",
    title: "Data storytelling competition",
    category: "competition",
    organizerLabel: "Analytics club program pattern",
    format: "online",
    location: "Remote",
    skillLevel: "beginner",
    typicalTiming: "Common during college technical festivals",
    description: "Turn an open dataset into a concise visual story with a transparent method and an actionable conclusion.",
    tags: ["data analysis", "statistics", "visual communication", "research"],
  },
  {
    id: "radar-design-case-challenge",
    title: "Student design case challenge",
    category: "competition",
    organizerLabel: "Design community program pattern",
    format: "online",
    location: "Remote",
    skillLevel: "beginner",
    typicalTiming: "Often runs as a one-to-two week brief",
    description: "Document user research, alternatives, and a prototype for a focused service or interface problem.",
    tags: ["ui design", "user research", "prototyping", "storytelling"],
  },
  {
    id: "radar-business-case-league",
    title: "Undergraduate business case league",
    category: "competition",
    organizerLabel: "Campus entrepreneurship network pattern",
    format: "hybrid",
    location: "Major campus hubs",
    skillLevel: "intermediate",
    typicalTiming: "Frequently aligned with annual college festivals",
    description: "Analyze a market problem, recommend a strategy, and defend the assumptions in a short team presentation.",
    tags: ["business", "market research", "finance", "public speaking"],
  },
  {
    id: "radar-research-poster",
    title: "Student research poster showcase",
    category: "competition",
    organizerLabel: "Academic conference program pattern",
    format: "in-person",
    location: "Regional university hubs",
    skillLevel: "intermediate",
    typicalTiming: "Common near the end of a semester",
    description: "Present a small original study or literature synthesis through a poster, abstract, and short question session.",
    tags: ["research methods", "science", "public speaking", "visual communication"],
  },
  {
    id: "radar-first-issue-cohort",
    title: "Open-source first-issue cohort",
    category: "open-source",
    organizerLabel: "Maintainer community program pattern",
    format: "online",
    location: "Remote",
    skillLevel: "beginner",
    typicalTiming: "Cohorts often run for four to six weeks",
    description: "Learn contribution workflow, improve documentation, and ship a reviewed first pull request with maintainer guidance.",
    tags: ["programming", "version control", "technical writing", "portfolio building"],
  },
  {
    id: "radar-accessibility-audit",
    title: "Open accessibility audit drive",
    category: "open-source",
    organizerLabel: "Digital inclusion community pattern",
    format: "online",
    location: "Remote",
    skillLevel: "beginner",
    typicalTiming: "Usually organized as a focused community month",
    description: "Test a public project for keyboard, contrast, and semantic issues, then submit reproducible fixes or reports.",
    tags: ["ui design", "web development", "quality assurance", "social impact"],
  },
  {
    id: "radar-open-data-cleanup",
    title: "Open-data quality contribution",
    category: "open-source",
    organizerLabel: "Civic data community pattern",
    format: "online",
    location: "Remote",
    skillLevel: "intermediate",
    typicalTiming: "Tasks are commonly available in rolling batches",
    description: "Validate, document, and improve a public dataset while keeping a reproducible record of every transformation.",
    tags: ["data analysis", "statistics", "technical writing", "public policy"],
  },
  {
    id: "radar-career-studio",
    title: "Career portfolio studio",
    category: "event",
    organizerLabel: "Student career center event pattern",
    format: "hybrid",
    location: "Regional campus hubs",
    skillLevel: "all-levels",
    typicalTiming: "Often scheduled before internship and placement seasons",
    description: "A guided review session for one portfolio artifact, a concise introduction, and an evidence-based next step.",
    tags: ["portfolio building", "career planning", "communication", "employability"],
  },
  {
    id: "radar-founder-ama",
    title: "Early-career founder AMA",
    category: "event",
    organizerLabel: "Startup community event pattern",
    format: "online",
    location: "Remote",
    skillLevel: "all-levels",
    typicalTiming: "Usually offered as a monthly community session",
    description: "A moderated session about customer discovery, early roles, and how student projects can demonstrate initiative.",
    tags: ["entrepreneurship", "customer discovery", "business", "career planning"],
  },
  {
    id: "radar-practice-interview-circle",
    title: "Peer interview practice circle",
    category: "event",
    organizerLabel: "Student placement community pattern",
    format: "hybrid",
    location: "India-wide chapters",
    skillLevel: "all-levels",
    typicalTiming: "Most common ahead of campus placement cycles",
    description: "Practice structured responses, exchange rubric-based feedback, and leave with one measurable communication goal.",
    tags: ["interview preparation", "public speaking", "communication", "employability"],
  },
];
