export interface LearningResourceEntry {
  id: string;
  title: string;
  provider: string;
  type: "course" | "docs" | "book" | "practice" | "video" | "certificate";
  url: string;
  free: boolean;
  skillTags: string[];
  styleTags: Array<"video" | "reading" | "hands-on" | "blended">;
  estMinutes: number;
}

export const learningResourceBank: LearningResourceEntry[] = [
  { id: "res-cs50", title: "CS50: Introduction to Computer Science", provider: "Harvard", type: "course", url: "https://cs50.harvard.edu/x/", free: true, skillTags: ["Programming", "Computer science", "Problem solving"], styleTags: ["video", "hands-on", "blended"], estMinutes: 7200 },
  { id: "res-mdn", title: "MDN Web Development Guides", provider: "Mozilla", type: "docs", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development", free: true, skillTags: ["Programming", "Web development", "Technical writing"], styleTags: ["reading", "hands-on"], estMinutes: 2400 },
  { id: "res-odin", title: "The Odin Project", provider: "The Odin Project", type: "course", url: "https://www.theodinproject.com/", free: true, skillTags: ["Programming", "Web development", "Portfolio building"], styleTags: ["reading", "hands-on"], estMinutes: 9000 },
  { id: "res-fullstackopen", title: "Full Stack Open", provider: "University of Helsinki", type: "course", url: "https://fullstackopen.com/en/", free: true, skillTags: ["Programming", "Web development", "Systems thinking"], styleTags: ["reading", "hands-on"], estMinutes: 7200 },
  { id: "res-kaggle", title: "Kaggle Learn", provider: "Kaggle", type: "practice", url: "https://www.kaggle.com/learn", free: true, skillTags: ["Data analysis", "Statistics", "Machine learning", "Programming"], styleTags: ["hands-on", "reading"], estMinutes: 1800 },
  { id: "res-python", title: "The Python Tutorial", provider: "Python Software Foundation", type: "docs", url: "https://docs.python.org/3/tutorial/", free: true, skillTags: ["Programming", "Data analysis", "Automation"], styleTags: ["reading", "hands-on"], estMinutes: 1200 },
  { id: "res-sqlbolt", title: "SQLBolt Interactive Lessons", provider: "SQLBolt", type: "practice", url: "https://sqlbolt.com/", free: true, skillTags: ["Data analysis", "Database fundamentals", "Analytics"], styleTags: ["hands-on"], estMinutes: 360 },
  { id: "res-github-skills", title: "GitHub Skills", provider: "GitHub", type: "practice", url: "https://skills.github.com/", free: true, skillTags: ["Portfolio building", "Version control", "Programming"], styleTags: ["hands-on"], estMinutes: 480 },
  { id: "res-roadmap", title: "Developer Roadmaps", provider: "roadmap.sh", type: "docs", url: "https://roadmap.sh/", free: true, skillTags: ["Programming", "Cloud fundamentals", "Cybersecurity", "Systems thinking"], styleTags: ["reading", "blended"], estMinutes: 300 },
  { id: "res-microsoft-learn", title: "Microsoft Learn", provider: "Microsoft", type: "certificate", url: "https://learn.microsoft.com/training/", free: true, skillTags: ["Cloud fundamentals", "Data analysis", "AI fundamentals", "Programming"], styleTags: ["reading", "hands-on", "blended"], estMinutes: 1200 },
  { id: "res-aws", title: "AWS Skill Builder", provider: "Amazon Web Services", type: "course", url: "https://skillbuilder.aws/", free: false, skillTags: ["Cloud fundamentals", "Systems thinking", "Cybersecurity"], styleTags: ["video", "hands-on", "blended"], estMinutes: 1200 },
  { id: "res-google-ai", title: "Google Machine Learning Crash Course", provider: "Google", type: "course", url: "https://developers.google.com/machine-learning/crash-course", free: true, skillTags: ["Machine learning", "Statistics", "Programming"], styleTags: ["video", "reading", "hands-on"], estMinutes: 900 },
  { id: "res-nptel", title: "NPTEL Online Courses", provider: "NPTEL", type: "course", url: "https://nptel.ac.in/courses", free: true, skillTags: ["Engineering fundamentals", "Computer science", "Economics", "Research methods"], styleTags: ["video", "reading"], estMinutes: 2400 },
  { id: "res-swayam", title: "SWAYAM Course Catalogue", provider: "Government of India", type: "course", url: "https://swayam.gov.in/", free: true, skillTags: ["Engineering fundamentals", "Business", "Education", "Research methods"], styleTags: ["video", "reading", "blended"], estMinutes: 2400 },
  { id: "res-mitocw", title: "MIT OpenCourseWare", provider: "MIT", type: "course", url: "https://ocw.mit.edu/", free: true, skillTags: ["Mathematics", "Physics", "Engineering fundamentals", "Economics"], styleTags: ["video", "reading"], estMinutes: 3000 },
  { id: "res-khan", title: "Khan Academy India", provider: "Khan Academy", type: "course", url: "https://www.khanacademy.org/", free: true, skillTags: ["Mathematics", "Statistics", "Economics", "Science"], styleTags: ["video", "hands-on"], estMinutes: 1200 },
  { id: "res-figma", title: "Figma Design Resources", provider: "Figma", type: "docs", url: "https://help.figma.com/hc/en-us/categories/360002051613-Get-started", free: true, skillTags: ["Prototyping", "Visual communication", "UI design"], styleTags: ["video", "reading", "hands-on"], estMinutes: 480 },
  { id: "res-nng", title: "UX Research and Design Articles", provider: "Nielsen Norman Group", type: "docs", url: "https://www.nngroup.com/articles/", free: true, skillTags: ["User research", "Interaction design", "Service design"], styleTags: ["reading"], estMinutes: 600 },
  { id: "res-canva", title: "Canva Design School", provider: "Canva", type: "course", url: "https://www.canva.com/designschool/", free: true, skillTags: ["Visual communication", "Brand strategy", "Content creation"], styleTags: ["video", "hands-on"], estMinutes: 480 },
  { id: "res-hubspot", title: "HubSpot Academy", provider: "HubSpot", type: "certificate", url: "https://academy.hubspot.com/", free: true, skillTags: ["Market research", "Digital marketing", "Content strategy", "Sales"], styleTags: ["video", "blended"], estMinutes: 900 },
  { id: "res-sebi", title: "Investor Education Resources", provider: "SEBI", type: "docs", url: "https://investor.sebi.gov.in/", free: true, skillTags: ["Finance", "Investing", "Risk assessment"], styleTags: ["reading"], estMinutes: 300 },
  { id: "res-rbi", title: "Financial Education Initiative", provider: "Reserve Bank of India", type: "docs", url: "https://www.rbi.org.in/financialeducation/", free: true, skillTags: ["Finance", "Economics", "Financial literacy"], styleTags: ["reading"], estMinutes: 300 },
  { id: "res-indiacode", title: "India Code", provider: "Government of India", type: "docs", url: "https://www.indiacode.nic.in/", free: true, skillTags: ["Legal reasoning", "Policy analysis", "Research"], styleTags: ["reading"], estMinutes: 600 },
  { id: "res-worldbank", title: "Open Learning Campus", provider: "World Bank", type: "course", url: "https://olc.worldbank.org/", free: true, skillTags: ["Policy analysis", "Development studies", "Program management"], styleTags: ["video", "reading"], estMinutes: 900 },
  { id: "res-who", title: "OpenWHO Courses", provider: "World Health Organization", type: "course", url: "https://openwho.org/", free: true, skillTags: ["Public health", "Clinical reasoning", "Emergency response"], styleTags: ["video", "reading"], estMinutes: 900 },
  { id: "res-psych", title: "Introduction to Psychology", provider: "OpenStax", type: "book", url: "https://openstax.org/details/books/psychology-2e", free: true, skillTags: ["Psychology", "Behavioral research", "Active listening"], styleTags: ["reading"], estMinutes: 2400 },
  { id: "res-arduino", title: "Arduino Project Hub", provider: "Arduino", type: "practice", url: "https://projecthub.arduino.cc/", free: true, skillTags: ["Electronics", "Robotics", "Embedded systems", "Portfolio building"], styleTags: ["hands-on"], estMinutes: 900 },
  { id: "res-autodesk", title: "Autodesk Learning", provider: "Autodesk", type: "course", url: "https://www.autodesk.com/learn", free: true, skillTags: ["CAD", "Architecture", "Engineering fundamentals", "3D fundamentals"], styleTags: ["video", "hands-on"], estMinutes: 900 },
  { id: "res-nasa", title: "NASA STEM Resources", provider: "NASA", type: "docs", url: "https://www.nasa.gov/learning-resources/", free: true, skillTags: ["Physics", "Space systems", "Earth science"], styleTags: ["video", "reading", "hands-on"], estMinutes: 600 },
  { id: "res-qgis", title: "QGIS Training Manual", provider: "QGIS", type: "docs", url: "https://docs.qgis.org/latest/en/docs/training_manual/", free: true, skillTags: ["Geospatial analysis", "Environmental science", "Urban planning"], styleTags: ["reading", "hands-on"], estMinutes: 1200 },
  { id: "res-exercism", title: "Exercism Practice Tracks", provider: "Exercism", type: "practice", url: "https://exercism.org/tracks", free: true, skillTags: ["Programming", "Problem solving", "Code review"], styleTags: ["hands-on"], estMinutes: 900 },
  { id: "res-leetcode", title: "LeetCode Practice", provider: "LeetCode", type: "practice", url: "https://leetcode.com/problemset/", free: false, skillTags: ["Data structures", "Algorithms", "Interview preparation"], styleTags: ["hands-on"], estMinutes: 1200 },
  { id: "res-ted", title: "TED Public Speaking Playlist", provider: "TED", type: "video", url: "https://www.ted.com/playlists/226/before_public_speaking", free: true, skillTags: ["Public speaking", "Communication", "Storytelling"], styleTags: ["video"], estMinutes: 180 },
  { id: "res-pmi", title: "Project Management Basics", provider: "PMI", type: "docs", url: "https://www.pmi.org/about/learn-about-pmi/what-is-project-management", free: true, skillTags: ["Project management", "Prioritisation", "Operations planning"], styleTags: ["reading"], estMinutes: 180 },
  { id: "res-ilo", title: "Skills and Employability Resources", provider: "International Labour Organization", type: "docs", url: "https://www.ilo.org/skills", free: true, skillTags: ["Career planning", "Employability", "Workplace communication"], styleTags: ["reading", "video"], estMinutes: 360 },
  { id: "res-startup-india", title: "Startup India Learning Program", provider: "Startup India", type: "course", url: "https://www.startupindia.gov.in/content/sih/en/reources/online-courses.html", free: true, skillTags: ["Customer discovery", "Entrepreneurship", "Business"], styleTags: ["video", "reading"], estMinutes: 600 },
];
