"use client";

import { useMemo, useState } from "react";
import { BarChart3, Calculator, CheckCircle2, Clock3, Plus, Sparkles, Target } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

function Header({ icon: Icon, title, description }: { icon: typeof Sparkles; title: string; description: string }) {
  return <section className="rounded-3xl border border-border bg-card p-6 sm:p-9"><Badge>Interactive planner</Badge><div className="mt-5 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon aria-hidden="true" /></span><div><h1 className="text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div></section>;
}

export function CareerSimulatorTool() {
  const [role, setRole] = useState("Data Analyst");
  const [hours, setHours] = useState(8);
  const [result, setResult] = useState(false);
  const weeks = Math.max(12, Math.round(360 / Math.max(1, hours)));
  return <div className="mx-auto max-w-6xl space-y-6 pb-16"><Header icon={Target} title="Career Simulator" description="Turn a target role into a practical, adjustable readiness plan." /><section className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><Card><CardHeader><CardTitle>Set your scenario</CardTitle><CardDescription>Use your real weekly availability. Results update from your input.</CardDescription></CardHeader><CardContent className="space-y-4"><label className="grid gap-2 text-sm font-medium">Target role<Input value={role} onChange={(event) => setRole(event.target.value)} /></label><label className="grid gap-2 text-sm font-medium">Hours available each week<Input type="number" min="1" max="60" value={hours} onChange={(event) => setHours(Number(event.target.value))} /></label><Button className="w-full" onClick={() => setResult(true)}><Sparkles aria-hidden="true" />Generate plan</Button></CardContent></Card>{result ? <Card className="p-6"><Badge variant="success">Scenario ready</Badge><h2 className="mt-4 text-2xl font-semibold">Your {role || "target role"} pathway</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">At {hours} hours per week, a focused foundation takes about {weeks} weeks. This is a planning estimate—not a job or salary prediction.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Foundation", `${Math.round(weeks * .35)} weeks`, "Core concepts + 1 guided project"], ["Evidence", `${Math.round(weeks * .4)} weeks`, "2 portfolio projects + feedback"], ["Launch", `${Math.round(weeks * .25)} weeks`, "Applications, interviews, iteration"]].map(([name, time, text]) => <div key={name} className="rounded-xl border border-border bg-muted/30 p-4"><p className="font-medium">{name}</p><p className="mt-2 text-primary">{time}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{text}</p></div>)}</div></Card> : <Card className="grid min-h-80 place-items-center p-6 text-center"><div><Clock3 className="mx-auto size-8 text-muted-foreground" aria-hidden="true" /><p className="mt-3 font-medium">Ready when you are</p><p className="mt-1 text-sm text-muted-foreground">Create a scenario to see the milestones.</p></div></Card>}</section></div>;
}

export function WhatIfTool() {
  const [paths, setPaths] = useState(["B.Tech + campus projects", "BCA + self-paced portfolio"]);
  const [budget, setBudget] = useState(500000);
  const scores = useMemo(() => paths.map((path, index) => ({ path, score: Math.min(96, 58 + index * 8 + Math.round(Math.min(budget, 800000) / 80000)), time: index === 0 ? "4 years" : "3 years" })), [paths, budget]);
  return <div className="mx-auto max-w-6xl space-y-6 pb-16"><Header icon={BarChart3} title="What‑If Simulator" description="Compare real choices with transparent assumptions you control." /><section className="grid gap-6 lg:grid-cols-[0.7fr_1.3fr]"><Card><CardHeader><CardTitle>Compare paths</CardTitle><CardDescription>Scores are fit estimates, not admissions or employment outcomes.</CardDescription></CardHeader><CardContent className="space-y-4">{paths.map((path, index) => <label className="grid gap-2 text-sm font-medium" key={index}>Path {index + 1}<Input value={path} onChange={(event) => setPaths((current) => current.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /></label>)}<label className="grid gap-2 text-sm font-medium">Total education budget (₹)<Input type="number" min="0" value={budget} onChange={(event) => setBudget(Number(event.target.value))} /></label><Button variant="secondary" onClick={() => setPaths((current) => current.length < 3 ? [...current, "New option"] : current)} disabled={paths.length >= 3}><Plus aria-hidden="true" />Add third path</Button></CardContent></Card><Card className="p-6"><h2 className="text-xl font-semibold">Comparison</h2><div className="mt-5 space-y-5">{scores.map((item) => <div key={item.path} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{item.path || "Untitled path"}</p><Badge variant="success">{item.score}% planning fit</Badge></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full signature-gradient" style={{ width: `${item.score}%` }} /></div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>Expected study horizon: {item.time}</span><span>Budget input: ₹{budget.toLocaleString("en-IN")}</span></div></div>)}</div></Card></section></div>;
}

export function FinancialPlannerTool() {
  const [cost, setCost] = useState(600000);
  const [scholarship, setScholarship] = useState(80000);
  const [years, setYears] = useState(4);
  const remaining = Math.max(0, cost - scholarship);
  const monthly = Math.round(remaining / Math.max(1, years * 12));
  return <div className="mx-auto max-w-6xl space-y-6 pb-16"><Header icon={Calculator} title="Financial Planner" description="Model education costs with your own assumptions—not invented placement claims." /><section className="grid gap-6 lg:grid-cols-[0.7fr_1.3fr]"><Card><CardHeader><CardTitle>Your inputs</CardTitle><CardDescription>All values are editable estimates in Indian rupees.</CardDescription></CardHeader><CardContent className="space-y-4"><label className="grid gap-2 text-sm font-medium">Total course cost<Input type="number" min="0" value={cost} onChange={(event) => setCost(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-medium">Confirmed scholarship or support<Input type="number" min="0" value={scholarship} onChange={(event) => setScholarship(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-medium">Course duration (years)<Input type="number" min="1" max="8" value={years} onChange={(event) => setYears(Number(event.target.value))} /></label></CardContent></Card><Card className="p-6"><Badge>Live calculation</Badge><div className="mt-5 grid gap-4 sm:grid-cols-3">{[["Total cost", cost], ["Support", scholarship], ["Remaining", remaining]].map(([label, amount]) => <div key={String(label)} className="rounded-xl border border-border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">₹{Number(amount).toLocaleString("en-IN")}</p></div>)}</div><div className="mt-6 rounded-xl border border-primary/25 bg-primary/5 p-5"><p className="text-sm text-muted-foreground">Monthly savings target across {years} years</p><p className="mt-2 text-3xl font-semibold text-primary">₹{monthly.toLocaleString("en-IN")}</p><p className="mt-2 text-xs text-muted-foreground">This is a budget breakdown only. Check official fee notices and scholarship eligibility before deciding.</p></div></Card></section></div>;
}

export function ConfidenceJournalTool() {
  const [entry, setEntry] = useState(""); const [rating, setRating] = useState(3); const [entries, setEntries] = useState<Array<{ text: string; rating: number; date: string }>>([]);
  function save() { if (!entry.trim()) return; setEntries((current) => [{ text: entry.trim(), rating, date: new Date().toLocaleDateString("en-IN") }, ...current]); setEntry(""); }
  return <div className="mx-auto max-w-6xl space-y-6 pb-16"><Header icon={CheckCircle2} title="Confidence Journal" description="Capture how you feel about your direction and see your own reflection history." /><section className="grid gap-6 lg:grid-cols-[0.75fr_1.25fr]"><Card><CardHeader><CardTitle>New reflection</CardTitle><CardDescription>This stays private to your browser until your account sync is configured.</CardDescription></CardHeader><CardContent className="space-y-4"><label className="grid gap-2 text-sm font-medium">Confidence today: {rating}/5<input className="accent-primary" type="range" min="1" max="5" value={rating} onChange={(event) => setRating(Number(event.target.value))} /></label><label className="grid gap-2 text-sm font-medium">What felt clear or difficult today?<textarea className="min-h-32 rounded-md border border-input bg-background/70 p-3 text-sm outline-none focus:border-primary/55" value={entry} onChange={(event) => setEntry(event.target.value)} placeholder="Write a short reflection…" /></label><Button className="w-full" onClick={save}><CheckCircle2 aria-hidden="true" />Save reflection</Button></CardContent></Card><Card className="p-6"><h2 className="text-xl font-semibold">Your recent reflections</h2><div className="mt-4 space-y-3">{entries.length ? entries.map((item, index) => <div className="rounded-xl border border-border p-4" key={`${item.date}-${index}`}><div className="flex justify-between gap-3"><Badge variant="success">Confidence {item.rating}/5</Badge><span className="text-xs text-muted-foreground">{item.date}</span></div><p className="mt-3 text-sm leading-6">{item.text}</p></div>) : <p className="py-16 text-center text-sm text-muted-foreground">Your reflections will appear here after you save one.</p>}</div></Card></section></div>;
}
